languageCode: en
title: Core-Styles 3
baseURL: https://guides.webstop.com
enableInlineShortcodes: true
sectionPagesMenu: main
markup:
  goldmark:
    renderer:
      unsafe: true
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
      autoHeadingIDType: github
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ''
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: false
    noClasses: false
    tabWidth: 2
buildDrafts: true
buildFuture: true
enableRobotsTXT: true
metaDataFormat: yaml
disableKinds:
  - '404'
  - taxonomy
  - taxonomyTerm
  - RSS
publishDir: docs
module:
  mounts:
    - source: dist
      target: static/docs/3.0/dist
    - source: site/assets
      target: assets
    - source: site/content
      target: content
    - source: site/data
      target: data
    - source: site/layouts
      target: layouts
    - source: site/static
      target: static
params:
  icons_kit_key: 8bda546f76
  repo: https://github.com/webstop/core-styles-3
  website: https://guides.webstop.com
  build:
    version: 3.0.5
    name: core-styles-3
    description: Design System for Webstop's products.
    author: Greg Hemphill
    license: private
    buildDate: '2025-08-22T17:42:37.983Z'
    nodeVersion: v18.4.0
    repository: https://github.com/webstop/core-styles-3
    homepage: https://guides.webstop.com/
    versionMajor: 3
    versionMinor: 0
    versionPatch: 5
