#!/usr/bin/env bash

# The following stopped working
# docker-compose run --rm bash --version ; npm run watch

echo 'Once the shell prompt becomes available enter `npm run watch` (without the quotes) to start the watch script.'

docker run --rm -it -v $(pwd):/src klakegg/hugo:0.101.0-ext-alpine shell
